import Head from "next/head";
import Image from "next/image";
import { Box } from "@chakra-ui/react";
import Slider from "react-slick";

import { motion } from "framer-motion";

export default function Home() {
  const settings = {
    fade: true,
    infinite: true,
    speed: 2000,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 3000,
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        width="100%"
        height="100%"
        as={motion.div}
        exit={{ opacity: 0 }}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
      >
        <Slider {...settings}>
          <Box w="100vw" h="100vh" position="relative">
            <Image
              alt="image-1"
              src="/img-1.jpg"
              layout="fill"
              objectFit="cover"
              priority={true}
            />
          </Box>
          <Box w="100vw" h="100vh" position="relative">
            <Image
              alt="image-2"
              src="/img-2.jpg"
              layout="fill"
              objectFit="cover"
              priority={true}
            />
          </Box>
          <Box w="100vw" h="100vh" position="relative">
            <Image
              alt="image-3"
              src="/img-3.jpg"
              layout="fill"
              objectFit="cover"
              priority={true}
            />
          </Box>
          <Box w="100vw" h="100vh" position="relative">
            <Image
              alt="image-4"
              src="/img-4.jpg"
              layout="fill"
              objectFit="cover"
              priority={true}
            />
          </Box>
        </Slider>
      </Box>
    </>
  );
}
